on:
  push:

name: Android CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.7
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: 1.71
      #     override: true
      
      # - name: Set up cargo cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       rust/decentraland-godot-lib/target/
      #       rust/decentraland-godot-lib/Cargo.lock
      #       rust/xtask/target/
      #       rust/xtask/Cargo.lock
      #     key: android-cargo-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: android-cargo-
          
      # # Depedencies section
      # # => Android
      # - name: Install alsa and udev
      #   run: |
      #     sudo apt-get update
    
      # - name: Set up target platform
      #   run: |
      #     rustup target add aarch64-linux-android

      # # => All platforms
      # - name: cargo xtask install
      #   working-directory: rust/xtask
      #   run: cargo run -- install

      # # Build section
      # - name: cargo build
      #   working-directory: rust/decentraland-godot-lib
      #   run: |
      #     echo "TODO"
